rootProject.name = "commons-numbers"
include("commons-numbers-core")
include("commons-numbers-angle")
include("commons-numbers-arrays")
include("commons-numbers-combinatorics")
include("commons-numbers-complex")
include("commons-numbers-field")
include("commons-numbers-fraction")
include("commons-numbers-gamma")
include("commons-numbers-primes")
include("commons-numbers-quaternion")
include("commons-numbers-rootfinder")
